export const PRIMARY_APP_URL = "https://powershot.org";

export const POWERSHOT_DELIVER_CAPTURE = "POWERSHOT_DELIVER_CAPTURE";
export const POWERSHOT_BRIDGE_READY = "POWERSHOT_BRIDGE_READY";

export const POWERSHOT_CAPTURE_VISIBLE = "POWERSHOT_CAPTURE_VISIBLE";
export const POWERSHOT_CAPTURE_REGION = "POWERSHOT_CAPTURE_REGION";
export const POWERSHOT_SEND_BATCH = "POWERSHOT_SEND_BATCH";
export const POWERSHOT_TRAY_REMOVE = "POWERSHOT_TRAY_REMOVE";
export const POWERSHOT_TRAY_CLEAR = "POWERSHOT_TRAY_CLEAR";
export const POWERSHOT_TRAY_GET = "POWERSHOT_TRAY_GET";
export const POWERSHOT_TRAY_UPDATED = "POWERSHOT_TRAY_UPDATED";

export function buildExtractionUrl() {
  return `${PRIMARY_APP_URL}/new?source=extension`;
}

export const buildNewNoteUrl = buildExtractionUrl;
